multipart:
  max-file-size: 20mb
  max-request-size: 20mb

server:
  port: 7800

spring:
  autoconfigure:
    exclude: org.redisson.spring.cache.RedissonCacheStatisticsAutoConfiguration
  profiles:
    active: sz
  cache:
    ehcache:
      config: classpath:ehcache.xml
    type: ehcache
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

################ 日志打印配置 ######################
logging:
  level:
    root: info
    com.fuint: info


################ MyBatisPlus配置 ######################
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml